### ISSUE TITLE
The keyboard shortcut popup is too large on my 11inch macbook air

### ISSUE THREAD

**Issue by willmot** [humanmade/apollo#8]
Also it ends up under the header, should probably be on-top.

![screen shot 2014-10-05 at 22 24 34](https://cloud.githubusercontent.com/assets/308507/4519859/f6c6dfa8-4ccd-11e4-889a-b8991ebaf02f.png)

**Comment by richardswain** [comment]
@willmot Is this still an issue now the headers have gone?
The only issue I see is the width of the button here

![screen shot 2015-01-07 at 11 06 44](https://cloud.githubusercontent.com/assets/888319/5644954/328924e2-9661-11e4-8907-77e0574d2385.png)

**Comment by willmot** [comment]
Nope looks good now 👍
